[package]
name = "chat_app"
version = "0.1.0"
authors = ["Nnaemeka Nwankwo <codebasetwo@gmail.com>"]
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "chat_app"

[dependencies]
actix-web = "4"
actix-ws = "0.4.0"
actix-governor = "0.6"
anyhow = "1.0"
argon2 = "0.5.3"
chrono = { version = "0.4.22", default-features = false, features = ["clock", "serde"] }
config = "0.15.22"
futures-util = "0.3.32"
lettre = "0.11"
reqwest = { version = "0.13", features = ["json", "form"] }
rand = { version = "0.10", features = ["std_rng"] }
secrecy = { version = "0.8", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
tracing-log = "0.1" # helps to output not only logs of our application
tracing-actix-web = "0.7"
unicode-segmentation = "1.13.2"
uuid = { version = "1.23.1", features = ["v4", "serde"] }
validator = "0.20.0"
dotenvy = "0.15.7"

[dependencies.sqlx]
version = "0.8"
default-features = false
features = [
    "runtime-tokio",
    "tls-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate"
]

[dev-dependencies]
claims = "0.8.0"
