[package]
name = "chat_app"
version = "0.1.0"
authors = ["Nnaemeka Nwankwo <codebasetwo@gmail.com>"]
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "chat_app"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
config = "0.15.22"
argon2 = "0.5.3"
validator = "0.20.0"
unicode-segmentation = "1.13.2"
chrono = { version = "0.4.22", default-features = false, features = ["clock", "serde"] }
uuid = { version = "1.23.1", features = ["v4", "serde"] }
secrecy = { version = "0.8", features = ["serde"] }
thiserror = "2"
anyhow = "1.0"
rand = { version = "0.10", features = ["std_rng"] }
sha2 = "0.10"

[dependencies.sqlx]
version = "0.8"
default-features = false
features = [
    "runtime-tokio",
    "tls-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate"
]

[dev-dependencies]
claims = "0.8.0"